// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
}

ext {
    diasyncVersionName = providers.environmentVariable("DIASYNC_VERSION_NAME")
            .orElse("${providers.gradleProperty('diasyncReleaseMajor').get()}.0")
            .get()
    diasyncVersionCode = providers.environmentVariable("DIASYNC_VERSION_CODE")
            .map { Integer.parseInt(it) }
            .orElse(1)
            .get()
}
