plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'ru.krotarnya.diasync2.watchface'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "ru.krotarnya.diasync2.watchface"
        minSdk 33
        targetSdk 37
        versionCode 1
        versionName "1.0"

    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
}
